---

# - name: stop mysql
#   ansible.builtin.systemd:
#     name: "{{ mysql_service_name[ansible_os_family] }}" 
#     state: stopped 
#     enabled: yes

# - name: Cleanup
#   ansible.builtin.file:
#     path: "{{ clean_idx }}"
#     state: absent
#   loop:
#     - /etc/mysql
#     - /var/lib/mysql
#   loop_control:
#     loop_var: clean_idx

- set_fact:
    mysql_ip_address: "{{ item }}"
  when: "item | ipaddr( mysql_subnet )"
  with_items: "{{ ansible_all_ipv4_addresses }}"

- name: 'set fact: list gr_seeds'
  set_fact:
    gr_seeds: >-
      {{ groups['mysql'] | join(':33061,') }}:33061